### ISSUE TITLE
How to get GDT score?

### ISSUE THREAD

**Issue by Planet-KIM** [hypnopump/MiniFold#41]
- How to get GDT score this project? 
- Can you give me solutions?
- This project have "get GDT score function" pipeline?

**Comment by hypnopump** [comment]
Not in this repository. You can create your own implementation from the definition of the metric: https://www.predictioncenter.org/casp12/doc/help.html
or use the one provided here: https://github.com/lucidrains/alphafold2/blob/main/alphafold2_pytorch/utils.py#L887
