### ISSUE TITLE
How to make pssm file?

### ISSUE THREAD

**Issue by Planet-KIM** [hypnopump/MiniFold#42]
- I want to make pssm file. Because this file predict 3d structure?
- Please give me solutions.
- Do you have a "make pssm file function" pipeline?

**Comment by hypnopump** [comment]
Unfortunately, no. You need to get it on your own: https://www.ncbi.nlm.nih.gov/Class/Structure/pssm/pssm_viewer.cgi

**Comment by Planet-KIM** [comment]
@hypnopump Thank you for reply.
